export declare const SFDX_PROJECT_FILE = "sfdx-project.json";
export declare const SFDX_CONFIG_FILE = "sfdx-config.json";
export declare const SFDX_FOLDER = ".sfdx";
export declare const CLIENT_ID = "sfdx-vscode";
export declare const STATUS_BAR_MSG_TIMEOUT_MS = 5000;
export declare const APEX_CODE_DEBUG_LEVEL = "FINEST";
export declare const VISUALFORCE_DEBUG_LEVEL = "FINER";
export declare const SFDX_CONFIG_DISABLE_TELEMETRY = "disableTelemetry";
export declare const ENV_SFDX_DISABLE_TELEMETRY = "SFDX_DISABLE_TELEMETRY";
export declare const SFDX_CLI_DOWNLOAD_LINK = "https://developer.salesforce.com/tools/sfdxcli";
export declare const DEFAULT_USERNAME_KEY = "defaultusername";
export declare const DEFAULT_DEV_HUB_USERNAME_KEY = "defaultdevhubusername";
export declare const PKG_ID_PREFIX = "04t";
export declare const TELEMETRY_GLOBAL_VALUE = "sfdxTelemetryMessage";
export declare const TELEMETRY_OPT_OUT_LINK = "https://developer.salesforce.com/tools/vscode/en/faq/telemetry";
export declare const TELEMETRY_METADATA_COUNT = "metadataCount";
export declare const CONFIG_SET_EXECUTOR = "force_config_set_org_text";
export declare const CONFIG_SET_NAME = "force_config_set_title";
export declare const TABLE_NAME_COL = "table_header_name";
export declare const TABLE_VAL_COL = "table_header_value";
export declare const TABLE_SUCCESS_COL = "table_header_success";
export declare const BETA_DEPLOY_RETRIEVE = "experimental.deployRetrieve";
export declare const CONFLICT_DETECTION_ENABLED = "detectConflictsAtSync";
export declare const INTERNAL_DEVELOPMENT_FLAG = "internal-development";
export declare const PUSH_OR_DEPLOY_ON_SAVE_ENABLED = "push-or-deploy-on-save.enabled";
export declare const PREFER_DEPLOY_ON_SAVE_ENABLED = "push-or-deploy-on-save.preferDeployOnSave";
export declare const PUSH_OR_DEPLOY_ON_SAVE_OVERRIDE_CONFLICTS = "push-or-deploy-on-save.overrideConflictsOnPush";
export declare const RETRIEVE_TEST_CODE_COVERAGE = "retrieve-test-code-coverage";
export declare const SHOW_CLI_SUCCESS_INFO_MSG = "show-cli-success-msg";
export declare const TELEMETRY_ENABLED = "telemetry.enabled";
export declare const ENABLE_SOBJECT_REFRESH_ON_STARTUP = "enable-sobject-refresh-on-startup";
export declare const ENABLE_DEPLOY_AND_RETRIEVE_FOR_SOURCE_TRACKED_ORGS = "enableDeployAndRetrieveForSourceTrackedOrgs.enabled";
export declare const CLI: {
    AUTH_DEVICE_LOGIN: string;
    AUTH_WEB_LOGIN: string;
};
export declare const APEX_FILE_NAME_EXTENSION = ".apex";
export declare const SOQL_FILE_NAME_EXTENSION = ".soql";
export declare const AURA_PATH = "/force-app/main/default/aura/";
export declare const APEX_CLASSES_PATH = "/force-app/main/default/classes/";
export declare const LWC_PATH = "/force-app/main/default/lwc/";
export declare const FUNCTIONS_PATH = "/functions/";
export declare const ORG_OPEN_COMMAND = "sfdx.force.org.open";
